 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

app.get('/', (req, res) => {
  app.use(express.static(__dirname + 'views/index.html'));
});

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

